---

- name: installing packages insha Allah
  become: yes
  apt:
    name: python:3
    state: absent
    update_cache: yes

- name: create directory insha Allah
  file:
    path: ./basic-http-server
    state: directory

- name: install nginx insha Allah
  become: yes
  apt:
    name: nginx
    state: latest